#ifndef EXPORT_H
#define EXPORT_H

#ifdef _BUILDING_MYRIN
#define MYRIN_DLL_EXPORT  QX_DLL_EXPORT_HELPER
#else
#define MYRIN_DLL_EXPORT  QX_DLL_IMPORT_HELPER
#endif

#ifdef _BUILDING_MYRIN
#define QX_REGISTER_HPP_MYRIN  QX_REGISTER_HPP_EXPORT_DLL
#define QX_REGISTER_CPP_MYRIN  QX_REGISTER_CPP_EXPORT_DLL
#else
#define QX_REGISTER_HPP_MYRIN  QX_REGISTER_HPP_IMPORT_DLL
#define QX_REGISTER_CPP_MYRIN  QX_REGISTER_CPP_IMPORT_DLL
#endif

#endif // EXPORT_H
